meta_product_name: "Wackywine"
meta_title: "WackyWine - Making wine accessible to the youth"
meta_description: "Flipping the wine experience upside down by eliminating traditional jargon"
meta_image: "bannertwo.jpg" # should exist in `app/assets/images/`
